#!/usr/bin/env bash
# display outputs using case keyword

number=0
while [ $number -lt 20 ]
do
	echo "$number"
	case $number in
		"4")
		echo "bad luck from China";;
		"9")
		echo "bad luck from Japan";;
		"17")
		echo "bad luck from Italy";;
	esac
	(( number++ ))
done
